export enum SocketEvent {
  MESSAGE_SENT = "MESSAGE_SENT",
  DELETE_CONVERSATION = "DELETE_CONVERSATION",
  REMOVE_MESSAGE_FOR_ME = "REMOVE_MESSAGE_FOR_ME",
  UNSEND_MESSAGE = "UNSEND_MESSAGE",
  UPDATE_ACTIVE_STATUS = "UPDATE_ACTIVE_STATUS",
  USER_DISCONNECTED = "USER_DISCONNECTED",
}
